include:
  - project: 'crusoeenergy/tools'
    file: '/templates/go.gitlab-ci.yml'

variables: 
  MAJOR_VERSION: "0"
  MINOR_VERSION: "1"

analyze:
  variables:
    GOKART_CONFIG_LOC: $CI_PROJECT_DIR/.gokart/analyzers.yml
