include:
  - project: 'crusoeenergy/tools'
    file: '/templates/go.gitlab-ci.yml'

variables: # TODO(template) update these if you have go submodules
  MAJOR_VERSION: "0"
  MINOR_VERSION: "0"
  TAG_PREFIX: ""
