include:
  - project: 'crusoeenergy/tools'
    file: '/templates/go.gitlab-ci.yml'

variables: 
  MAJOR_VERSION: "0"
  MINOR_VERSION: "1"

analyze:
  variables:
    GOKART_CONFIG_LOC: $CI_PROJECT_DIR/.gokart/analyzers.yml

.code-changes: &code-changes
      changes:
        - .gitlab-ci.yml
        - Makefile
        - go.*

.swagger-changes: &swagger-changes
      changes:
        - swagger/**/*

.swagger-and-code-changes: &swagger-and-code-changes
      changes:
        - .gitlab-ci.yml
        - Makefile
        - go.*
        - swagger/**/*

test_and_lint:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_ID'
      changes: !reference [.swagger-and-code-changes, changes]

# trigger semantic versioning + tagging if .swagger-changes occur when pushing to the default branch
tag_semver:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: !reference [.swagger-changes, changes]
  needs: ["test_and_lint"]

# job that will ensure swagger pipeline is created when modifying swagger code
swagger-dummy:
  needs: []
  rules:
    - <<: *code-changes
      when: never
    - <<: *swagger-changes
      when: always
  script: "echo 'dummy swagger job'"

# update auotgen branch in cli
update-customer-cli:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "parent" && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "feature_branch" && $CI_PIPELINE_SOURCE == "merge_request_event"'
  script: 
      - apt update
      - apt install -y git openssh-client default-jre
      - eval $(ssh-agent -s)
      - echo "hello"
      - echo "$GIT_SSH_PRIV_KEY" | tr -d '\r' | ssh-add - > /dev/null
      - mkdir -p $HOME/.ssh
      - chmod 700 $HOME/.ssh
      - ssh-keyscan gitlab.com >> $HOME/.ssh/known_hosts
      - chmod 644 $HOME/.ssh/known_hosts
      - git config --global user.email ${GITLAB_USER_EMAIL}
      - git config --global user.name "Gitlab Runner"

      # Define the file path
      - JSON_CONTENT=$(cat swagger/v1alpha5/swagger.json)
      - git fetch --tags
      - LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1

      # Clone the target repository
      - git clone git@gitlab.com:crusoeenergy/island/external/customer-cli.git

      - cd customer-cli

      - git fetch origin
      - echo "hello"
        
      - git checkout add_autogen_scripts
      
      # Navigate to the specific directory
      - cd scripts/update_autogen
        
      # Run the script
      - echo "$JSON_CONTENT" | ./update_autogen.sh