include:
  - project: 'crusoeenergy/tools'
    file: '/templates/go.gitlab-ci.yml'

variables: 
  MAJOR_VERSION: "0"
  MINOR_VERSION: "1"

analyze:
  variables:
    GOKART_CONFIG_LOC: $CI_PROJECT_DIR/.gokart/analyzers.yml

.code-changes: &code-changes
      changes:
        - .gitlab-ci.yml
        - Makefile
        - go.*

.swagger-changes: &swagger-changes
      changes:
        - swagger/**/*

.swagger-and-code-changes: &swagger-and-code-changes
      changes:
        - .gitlab-ci.yml
        - Makefile
        - go.*
        - swagger/**/*

test_and_lint:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "auto-gen" || $CI_MERGE_REQUEST_ID'
      changes: !reference [.swagger-and-code-changes, changes]

# trigger semantic versioning + tagging if .swagger-changes occur when pushing to the default branch
tag_semver:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: !reference [.swagger-changes, changes]
  needs: ["test_and_lint"]

# job that will ensure swagger pipeline is created when modifying swagger code
swagger-dummy:
  needs: []
  rules:
    - <<: *code-changes
      when: never
    - <<: *swagger-changes
      when: always
  script: "echo 'dummy swagger job'"
