/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// OrganizationUsage is the project-level usage of products across an organization.
type CustomerOrganizationUsage struct {
	Items []CustomerProductProjectUsage `json:"items,omitempty"`
}
