/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SelfServeFlavor struct {
	// Flavor type identifier.
	FlavorType string `json:"flavor_type,omitempty"`
	// GPU type used by this flavor.
	GpuType string `json:"gpu_type,omitempty"`
	// GPUs per instance.
	GpusPerInstance int32 `json:"gpus_per_instance,omitempty"`
	// Flavor ID.
	Id string `json:"id,omitempty"`
	// Whether the flavor is suitable for LoRA adapters.
	LoraSuitable bool `json:"lora_suitable,omitempty"`
	// Model this flavor serves.
	ModelName string `json:"model_name,omitempty"`
	// Hourly price, as a decimal string.
	PricePerHour string `json:"price_per_hour,omitempty"`
	// Provider serving this flavor.
	Provider string `json:"provider,omitempty"`
	// Quantization applied, if any.
	Quantization string `json:"quantization,omitempty"`
}
