/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RenameModelRequest struct {
	// Current alias of the model.
	ModelAlias string `json:"model_alias"`
	// New alias for the model.
	NewAlias string `json:"new_alias"`
}
