/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KubernetesClusterLocationPreflight struct {
	// How the cluster's control plane would be hosted. \"pod\" means Crusoe hosts it and it consumes none of the project's VM capacity; \"vm\" means it runs on VMs in the project's location.
	ControlPlaneType string `json:"control_plane_type"`
	// VM types the control plane could use, in descending order of preference. Check availability of any one, in order: the cluster is created on the first with capacity. Empty when control_plane_type is \"pod\", because no VM is allocated — check capacity only when this list is non-empty.
	ControlPlaneVmTypes []string `json:"control_plane_vm_types"`
	// The location.
	Location string `json:"location"`
}
