/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Product is one catalog product: cross-family identity, lifecycle, and offerings. This message carries no API Framework options so it stays importable outside the customer-read gateway (e.g. from admin-gateway, which serves the same shape).
type CustomerProduct struct {
	// deprecate_at is when the product is, or was, deprecated; unset means not deprecated.
	DeprecateAt time.Time `json:"deprecate_at,omitempty"`
	// display_name is the human-facing product name.
	DisplayName string `json:"display_name,omitempty"`
	// featured_rank orders featured products for display; unset means not featured.
	FeaturedRank int32 `json:"featured_rank,omitempty"`
	// flags are authored labels used for filtering and merchandising.
	Flags []string `json:"flags,omitempty"`
	// id is the product's UUID.
	Id string `json:"id,omitempty"`
	// launch_at is when the product became, or becomes, available; unset means always available.
	LaunchAt time.Time `json:"launch_at,omitempty"`
	// logo_url is the product's logo image URL.
	LogoUrl string `json:"logo_url,omitempty"`
	// long_description is the full product description.
	LongDescription string                 `json:"long_description,omitempty"`
	ModelMetadata   *CustomerModelMetadata `json:"model_metadata,omitempty"`
	// new is true while the product is within its post-launch highlight window.
	New bool `json:"new,omitempty"`
	// offerings are the commercial offerings available for this product.
	Offerings []CustomerOffering `json:"offerings,omitempty"`
	// product_type identifies the product family (e.g. \"model\"). Open-ended: new families are additive and validated in-service, not enum values.
	ProductType string `json:"product_type,omitempty"`
	// short_description is a single-line summary.
	ShortDescription string `json:"short_description,omitempty"`
	// slug is the product's canonical, human-readable identifier (e.g. \"openai/gpt-oss-120b\").
	Slug string `json:"slug,omitempty"`
}
