/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CredentialSecrets struct {
	// Access token (e.g. a HuggingFace token). Write-only; omitted unless explicitly revealed.
	Token string `json:"token,omitempty"`
}
