/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IbPartition struct {
	// Identifier of the InfiniBand network the partition belongs to.
	IbNetworkId string `json:"ib_network_id"`
	// Unique identifier of the InfiniBand partition, assigned at creation.
	Id string `json:"id"`
	// Name of the InfiniBand partition.
	Name string `json:"name"`
}
