/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KubernetesNodePoolPatchRequest struct {
	// Action to perform on the node pool: RESERVE, UNRESERVE, or UPDATE. RESERVE and UNRESERVE operations are done synchronously, and so will have succeeded with a 200 response. Defaults to UPDATE if no action is specified.
	Action string `json:"action"`
	// New number of nodes in the node pool.
	Count int64 `json:"count"`
	// Whether the first local ephemeral NVMe disk is used for containerd storage.
	EphemeralStorageForContainerd bool `json:"ephemeral_storage_for_containerd"`
	// New labels for the node pool. Labels provided in the PATCH request do not modify existing nodes, but apply to any newly created nodes.
	NodeLabels map[string]string `json:"node_labels"`
	// New Kubernetes node pool version for newly created VMs.
	NodePoolVersion string `json:"node_pool_version"`
	// New taints for nodes in this node pool. Taints provided in the PATCH request do not modify existing nodes, but apply to any newly created nodes. This field has three behaviors: Omitted (null): existing taints are left unchanged. Empty array ([]): all existing taints are cleared. Non-empty array: existing taints are fully replaced by the provided list. Each (key, effect) pair in the list must be unique. Up to 50 taints are allowed. See KubernetesNodeTaint for per-field format rules.
	NodeTaints []KubernetesNodeTaint `json:"node_taints"`
	// New reservation ID for the node pool.
	ReservationId string `json:"reservation_id"`
	// New SSH public key to use for all VMs created from this node pool.
	SshPublicKey string `json:"ssh_public_key"`
}
