/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkTarget struct {
	// CIDR block, or an IP address that is converted to a CIDR. Mutually exclusive with resource_id.
	Cidr string `json:"cidr,omitempty"`
	// Unique identifier of a backend resource. Mutually exclusive with cidr.
	ResourceId string `json:"resource_id,omitempty"`
}
