/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HostChannelAdapter struct {
	// Globally unique identifier (GUID) of the host channel adapter.
	Guid          string `json:"guid"`
	IbNetworkId   string `json:"ib_network_id"`
	IbPartitionId string `json:"ib_partition_id"`
	// Identifier of the transport network the host channel adapter is attached to.
	TransportNetworkId string `json:"transport_network_id"`
	// Identifier of the transport partition the host channel adapter is attached to.
	TransportPartitionId string `json:"transport_partition_id"`
	// Transport type of the host channel adapter.
	Type_ string `json:"type"`
}
