/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeployedModelEntry struct {
	Architecture *FoundryArchitecture `json:"architecture,omitempty"`
	// Maximum context length supported by the model.
	ContextLength int32 `json:"context_length,omitempty"`
	// Unix timestamp when the model was created.
	Created int64 `json:"created,omitempty"`
	// Whether the model is currently deployed and serving.
	Deployed bool `json:"deployed,omitempty"`
	// Human-readable description of the model.
	Description string `json:"description,omitempty"`
	// URL of the model icon.
	Icon string `json:"icon,omitempty"`
	// Model endpoint ID.
	Id string `json:"id,omitempty"`
	// Whether the model can be used with rolling deployments.
	IsAvailableToRollingDeployment bool `json:"is_available_to_rolling_deployment,omitempty"`
	// Whether usage of the model is billed by token.
	IsBilledByToken bool `json:"is_billed_by_token,omitempty"`
	// Underlying (served) model name.
	ModelName string `json:"model_name,omitempty"`
	// Display name of the model.
	Name string `json:"name,omitempty"`
	// Owner of the model.
	OwnedBy string `json:"owned_by,omitempty"`
	// Quantization applied to the model, if any.
	Quantization string `json:"quantization,omitempty"`
	// Region the model is served in.
	Region string `json:"region,omitempty"`
	// Serving status of the model.
	Status string `json:"status,omitempty"`
	// Inference parameters supported by the model.
	SupportedParameters []string `json:"supported_parameters,omitempty"`
	// Tags associated with the model.
	Tags []string `json:"tags,omitempty"`
	// Model type (e.g. \"base_model\", \"adapter\").
	Type_ string `json:"type,omitempty"`
}
