/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DeploymentProgress struct {
	// Human-readable progress message.
	Message string `json:"message,omitempty"`
	// Completion percentage (0-100).
	Percent int32 `json:"percent,omitempty"`
	// RFC 3339 timestamp of the last progress update.
	UpdatedAt string `json:"updated_at,omitempty"`
}
