/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This is the REST-friendly model for the `BucketInfo` proto.
type S3Bucket struct {
	// Archive timestamp of the bucket, in RFC3339 format.
	ArchivedAt string `json:"archived_at,omitempty"`
	// Size of the bucket, in GiB.
	BucketSize float32 `json:"bucket_size,omitempty"`
	// Creation timestamp of the bucket, in RFC3339 format.
	CreatedAt string `json:"created_at"`
	// Location where the bucket is hosted.
	Location string `json:"location"`
	// Name of the bucket.
	Name string `json:"name"`
	// Whether object lock is enabled.
	ObjectLockEnabled bool `json:"object_lock_enabled"`
	// ID of the project that owns the bucket.
	ProjectId     string `json:"project_id"`
	RetentionMode string `json:"retention_mode,omitempty"`
	// Length of the object lock retention period, in the unit given by retention_period_unit.
	RetentionPeriod     int32  `json:"retention_period,omitempty"`
	RetentionPeriodUnit string `json:"retention_period_unit,omitempty"`
	// Endpoint URL for accessing the bucket.
	S3Url string `json:"s3_url,omitempty"`
	// Tags applied to the bucket as key-value pairs.
	Tags map[string]string `json:"tags,omitempty"`
	// Last update timestamp of the bucket, in RFC3339 format.
	UpdatedAt string `json:"updated_at"`
	// ID of the S3 user that owns the bucket.
	UserId          string `json:"user_id"`
	VersioningState string `json:"versioning_state"`
}
