/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VpcFirewallRulesPatchRequest struct {
	// Destination ports the rule matches. Each entry is a single port or a port range (for example, 3000-8080).
	DestinationPorts []string `json:"destination_ports,omitempty"`
	// Destinations the rule matches, given as CIDR blocks or resource IDs.
	Destinations []FirewallRuleObject `json:"destinations,omitempty"`
	// New name for the firewall rule.
	Name string `json:"name,omitempty"`
	// Network protocols the rule matches (for example, tcp, udp).
	Protocols []string `json:"protocols,omitempty"`
	// Source ports the rule matches. Each entry is a single port or a port range (for example, 3000-8080).
	SourcePorts []string `json:"source_ports,omitempty"`
	// Sources the rule matches, given as CIDR blocks or resource IDs.
	Sources []FirewallRuleObject `json:"sources,omitempty"`
}
