/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ProductProjectUsage is the usage of a product within a project for a single date.
type CustomerProductProjectUsage struct {
	BillableMetric string  `json:"billable_metric,omitempty"`
	Date           string  `json:"date,omitempty"`
	ProjectId      string  `json:"project_id,omitempty"`
	Quantity       float64 `json:"quantity,omitempty"`
	Region         string  `json:"region,omitempty"`
	ReservationId  string  `json:"reservation_id,omitempty"`
	ResourceType   string  `json:"resource_type,omitempty"`
}
