/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SelfServeActivityEvent struct {
	// Event type identifier.
	EventType string `json:"event_type,omitempty"`
	// Human-readable event message.
	Message string `json:"message,omitempty"`
	// RFC 3339 timestamp of the event.
	Timestamp string `json:"timestamp,omitempty"`
	// Short event title.
	Title string `json:"title,omitempty"`
	// Identity that triggered the event.
	UpdatedBy string `json:"updated_by,omitempty"`
}
