/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This allows the Kubernetes API server to authenticate users via an external OIDC provider.
type OidcAuthConfig struct {
	// PEM-encoded certificate authority certificate used to validate the OIDC server's certificate.
	CaCert string `json:"ca_cert,omitempty"`
	// Client ID for the OpenID Connect client.
	ClientId string `json:"client_id,omitempty"`
	// Claim used to identify the user's groups.
	GroupsClaim string `json:"groups_claim,omitempty"`
	// URL of the OpenID Connect issuer.
	IssuerUrl string `json:"issuer_url,omitempty"`
	// Claim used to identify the user. Defaults to 'sub'.
	UsernameClaim string `json:"username_claim,omitempty"`
	// Prefix added before the username to avoid name conflicts.
	UsernamePrefix string `json:"username_prefix,omitempty"`
}
