/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IbPartitionsPostRequestV1 struct {
	// ID of the InfiniBand network to create the partition in.
	IbNetworkId string `json:"ib_network_id"`
	// Name for the new InfiniBand partition.
	Name string `json:"name"`
}
