/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KubernetesNodePoolsVersionInfo struct {
	// The version name of Crusoe's Kubernetes node pools.
	NodePoolVersionName string `json:"node_pool_version_name"`
	// Features supported by this node pool version. Possible values today: \"node_taints\", \"ephemeral_storage_for_containerd\". New feature names may be added over time. API consumers should ignore unrecognized feature names.
	SupportedFeatures []string `json:"supported_features"`
	// A list of tags associated with the version.
	Tags           []string        `json:"tags"`
	VersionDetails *VersionDetails `json:"version_details"`
}
