/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VpcNetwork struct {
	Cidr    string   `json:"cidr,omitempty"`
	Gateway string   `json:"gateway,omitempty"`
	Id      string   `json:"id,omitempty"`
	Name    string   `json:"name,omitempty"`
	Subnets []string `json:"subnets,omitempty"`
}
