/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// InstanceV1Alpha4 contains identifying information about a vm instance for vms.instances endpoints.
type InstanceV1Alpha4 struct {
	CommitmentEnd       string               `json:"commitment_end"`
	CommitmentPeriod    int64                `json:"commitment_period"`
	CreatedAt           string               `json:"created_at"`
	Disks               []AttachedDisk       `json:"disks"`
	HostChannelAdapters []HostChannelAdapter `json:"host_channel_adapters"`
	Id                  string               `json:"id"`
	Location            string               `json:"location"`
	Name                string               `json:"name"`
	NetworkInterfaces   []NetworkInterface   `json:"network_interfaces"`
	ProductName         string               `json:"product_name"`
	RoleId              string               `json:"role_id"`
	SshDestination      string               `json:"ssh_destination"`
	State               string               `json:"state"`
}
