/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DiskSnapshot struct {
	CreatedAt   string `json:"created_at,omitempty"`
	CreatedFrom string `json:"created_from,omitempty"`
	Id          string `json:"id,omitempty"`
	Size        string `json:"size,omitempty"`
	UpdatedAt   string `json:"updated_at,omitempty"`
}
