/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha3
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Billing struct {
	Balance               string `json:"balance,omitempty"`
	Delinquent            bool   `json:"delinquent,omitempty"`
	HasValidPaymentMethod bool   `json:"has_valid_payment_method,omitempty"`
}
