/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ListCreditsResponse is the response for CreditsService.ListCredits.
type CustomerListCreditsResponse struct {
	Credits  []CustomerCredit `json:"credits,omitempty"`
	Currency string           `json:"currency,omitempty"`
}
