/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PublicIpv4Address struct {
	// Public IPv4 address.
	Address string `json:"address"`
	// ID of the public IPv4 address.
	Id string `json:"id"`
	// Allocation type of the public IPv4 address (for example, dynamic).
	Type_ string `json:"type"`
}
