/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SlurmNodesetStatus struct {
	// ID of the worker nodeset.
	Id string `json:"id"`
	// Message describing why nodeset is not in STATE_RUNNING
	Issues []SlurmNodesetIssue `json:"issues,omitempty"`
	// Count of nodes that are not only \"running\" but have all slurm replicas running
	ReadyCount int64 `json:"ready_count"`
	// State of the slurm nodeset
	State string `json:"state"`
}
