/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ListUserCredentialsResponse is the response containing a user's identity credentials.
type CustomerListUserCredentialsResponse struct {
	// credentials is the user's credential types. Deprecated: use credentials_map instead.
	Credentials    []string                              `json:"credentials,omitempty"`
	CredentialsMap map[string]CustomerIdentityCredential `json:"credentials_map,omitempty"`
}
