/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// It includes the one-time-only secret key.
type CreateS3KeyResponse struct {
	// Access key ID used to authenticate S3 requests.
	AccessKeyId string `json:"access_key_id"`
	// Expiration timestamp of the S3 access key, in RFC3339 format.
	ExpireAt string `json:"expire_at,omitempty"`
	// Secret access key paired with the access key ID. Returned only once, at creation.
	SecretKey string `json:"secret_key"`
}
