/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Individual resources that use Operations should populate the `metadata` field with resource-specific information.
type Operation struct {
	CompletedAt string       `json:"completed_at"`
	Metadata    *interface{} `json:"metadata"`
	OperationId string       `json:"operation_id"`
	Result      *interface{} `json:"result,omitempty"`
	StartedAt   string       `json:"started_at"`
	State       string       `json:"state"`
}
