/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KubernetesSupportAccessRequest struct {
	// Requested support access role.
	AccessRole string `json:"access_role"`
	// Time when the certificate expires.
	CertExpiresAt string `json:"cert_expires_at,omitempty"`
	// Fingerprint of the certificate.
	CertFingerprint string `json:"cert_fingerprint,omitempty"`
	// Time when the most recent certificate was issued.
	CertIssuedAt string `json:"cert_issued_at,omitempty"`
	// Serial number of the certificate.
	CertSerial string `json:"cert_serial,omitempty"`
	// Time when access expires.
	ExpiresAt string `json:"expires_at,omitempty"`
	// Time when access was requested.
	RequestedAt string `json:"requested_at,omitempty"`
	// ID of the user who requested access.
	RequestorId string `json:"requestor_id,omitempty"`
	// Name of the team requesting support access.
	RequestorTeam string `json:"requestor_team,omitempty"`
	// Reason given for requesting support access.
	SupportReason string `json:"support_reason,omitempty"`
	// Ticket associated with the support access request.
	TicketRef string `json:"ticket_ref,omitempty"`
}
