/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ListInstanceTemplatesResponseV1Alpha5 is the resource response type for GET requests to the InstanceTemplates endpoint.
type ListInstanceTemplatesResponseV1Alpha5 struct {
	Items []InstanceTemplate `json:"items"`
}
