/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IbPartition struct {
	IbNetworkId string `json:"ib_network_id"`
	Id          string `json:"id"`
	Name        string `json:"name"`
}
