/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RoleBindingInput struct {
	CustomerId    string `json:"customer_id"`
	RoleId        string `json:"role_id"`
	ScopeObjectId string `json:"scope_object_id"`
	ScopeType     string `json:"scope_type"`
}
