/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IbNetwork struct {
	// Available capacity in the network, broken down by VM slice type.
	Capacities []IbNetworkCapacity `json:"capacities"`
	// Unique identifier of the Infiniband network.
	Id string `json:"id"`
	// Location of the Infiniband network.
	Location string `json:"location"`
	// Name of the Infiniband network.
	Name string `json:"name"`
}
