/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SlurmNodeSetStatus struct {
	// Message describing why node set is not in STATE_RUNNING
	Error_ string `json:"error,omitempty"`
	// ID of the worker node set.
	Id string `json:"id"`
	// Count of nodes that are not only \"running\" but have all slurm replicas running
	ReadyCount int64 `json:"ready_count"`
	// State of the slurm node set
	State string `json:"state"`
}
