/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// UsageOptions contains the values which exist for the fields which we allow filtering on for the usageByProjectGet endpoint.
type UsageOptions struct {
	EndDate       string   `json:"end_date"`
	Projects      []string `json:"projects"`
	Regions       []string `json:"regions"`
	ResourceTypes []string `json:"resource_types"`
	StartDate     string   `json:"start_date"`
}
