/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// UpdateOrganizationMFARequest is the request for setting an organization's required MFA methods.
type OrganizationsMfaServiceUpdateOrganizationMfaBody struct {
	IntendedMethods []string `json:"intended_methods,omitempty"`
}
