/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KubernetesNodePoolPatchRequest struct {
	// The action to perform on the NodePool. RESERVE and UNRESERVE operations are done synchronously, and so will have succeeded with a 200 response. Defaults to UPDATE if no action specified.
	Action string `json:"action"`
	// The number of nodes to be created.
	Count int64 `json:"count,omitempty"`
	// Labels assigned to the node pool. Labels provided in the PATCH request will not modify existing nodes, but will apply to any newly created nodes.
	NodeLabels map[string]string `json:"node_labels,omitempty"`
	// The reservation ID of the node pool.
	ReservationId string `json:"reservation_id,omitempty"`
}
