/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type HealthCheckOptions struct {
	FailureCount string `json:"failure_count,omitempty"`
	Interval     string `json:"interval,omitempty"`
	Port         string `json:"port"`
	SuccessCount string `json:"success_count,omitempty"`
	Timeout      string `json:"timeout,omitempty"`
}
