/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EntitiesPutPostRequest struct {
	BillingAddr      *BillingAddress `json:"billing_addr,omitempty"`
	OrganizationName string          `json:"organization_name,omitempty"`
}
