/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListActivityResponse struct {
	// Activity events, most recent first.
	Events []SelfServeActivityEvent `json:"events,omitempty"`
	// Cursor for the next page of events, if any.
	NextCursor string `json:"next_cursor,omitempty"`
}
