/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Credit is a single credit balance transaction for an organization.
type CustomerCredit struct {
	Amount  string `json:"amount,omitempty"`
	Balance string `json:"balance,omitempty"`
	Date    string `json:"date,omitempty"`
}
