/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListCreditBurnEventsResponse struct {
	BurnEvents []CreditBurnEvent `json:"burn_events"`
	// Base64 encoded token representing the next page. Empty if on the last page.
	NextPageToken string `json:"next_page_token,omitempty"`
	// Base64 encoded token representing the previous page. Empty if on the first page.
	PrevPageToken string `json:"prev_page_token,omitempty"`
}
