/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// KubernetesClusterPreflightResponse describes, per location, how a cluster created now in a project would be hosted.
type KubernetesClusterPreflightResponse struct {
	// Preflight result for each location.
	Locations []KubernetesClusterLocationPreflight `json:"locations"`
}
