/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InstanceTemplatePostRequestV1Alpha5 struct {
	Disks          []DiskTemplate `json:"disks,omitempty"`
	IbPartitionId  string         `json:"ib_partition_id,omitempty"`
	ImageName      string         `json:"image_name,omitempty"`
	Location       string         `json:"location,omitempty"`
	Name           string         `json:"name"`
	ShutdownScript string         `json:"shutdown_script,omitempty"`
	SshPublicKey   string         `json:"ssh_public_key"`
	StartupScript  string         `json:"startup_script,omitempty"`
	SubnetId       string         `json:"subnet_id,omitempty"`
	Type_          string         `json:"type"`
}
