/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateDeploymentRequest struct {
	// Updated deployment name.
	DeploymentName string `json:"deployment_name,omitempty"`
	// Updated replica count.
	Replicas int32 `json:"replicas,omitempty"`
}
