/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CreateSsoProviderRequest struct {
	ClientId     string   `json:"client_id"`
	EmailDomains []string `json:"email_domains"`
	IssuerUri    string   `json:"issuer_uri"`
}
