/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// optionally including an inline token when requested.
type CreateScimIntegrationResponse struct {
	ApiKeyInfo  *GeneratedLimitedUsageApiKey `json:"api_key_info,omitempty"`
	Integration *ScimIntegrationResponse     `json:"integration"`
}
