/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerProjectResources struct {
	Disks       *CustomerProjectResourceDetails `json:"disks,omitempty"`
	Images      *CustomerProjectResourceDetails `json:"images,omitempty"`
	Instances   *CustomerProjectResourceDetails `json:"instances,omitempty"`
	Snapshots   *CustomerProjectResourceDetails `json:"snapshots,omitempty"`
	VpcNetworks *CustomerProjectResourceDetails `json:"vpc_networks,omitempty"`
}
