/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SlurmClusterPostRequest struct {
	// Location to create the slurm cluster in.
	Location string `json:"location"`
	// Name of the slurm cluster.
	Name string `json:"name"`
	// If true, allows internal developers to create slurm clusters without shared volumes.
	SansSharedVolume bool `json:"sans_shared_volume,omitempty"`
	// The ID of the subnet to create the cluster in. Must be in the location specified. If not provided, the default subnet for the location will be used, if there is one.
	SubnetId string `json:"subnet_id,omitempty"`
	// A mapping of usernames to their SSH keys for accessing the cluster. Both the username and ssh key must be named attributes, as shown in the example
	UserList map[string]string `json:"user_list"`
}
