/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// InstanceV1Alpha5 contains identifying information about a vm instance for vms.instances endpoints.
type InstanceV1Alpha5 struct {
	CommitmentEnd string `json:"commitment_end,omitempty"`
	// commitment is no longer supported
	CommitmentPeriod       int64                   `json:"commitment_period,omitempty"`
	CreatedAt              string                  `json:"created_at"`
	Disks                  []AttachedDiskV1Alpha5  `json:"disks"`
	HostChannelAdapters    []HostChannelAdapter    `json:"host_channel_adapters"`
	Id                     string                  `json:"id"`
	InstanceGroupId        string                  `json:"instance_group_id,omitempty"`
	InstanceTemplateId     string                  `json:"instance_template_id,omitempty"`
	Location               string                  `json:"location"`
	MaintenancePolicy      string                  `json:"maintenance_policy"`
	Name                   string                  `json:"name"`
	NetworkInterfaces      []NetworkInterface      `json:"network_interfaces"`
	PodId                  string                  `json:"pod_id,omitempty"`
	ProjectId              string                  `json:"project_id"`
	ReservationId          string                  `json:"reservation_id,omitempty"`
	State                  string                  `json:"state"`
	Type_                  string                  `json:"type"`
	UpdatedAt              string                  `json:"updated_at"`
	VirtualizationFeatures *VirtualizationFeatures `json:"virtualization_features,omitempty"`
}
