/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SlurmClusterStatus struct {
	// Issues describing why the cluster is not in STATE_RUNNING.
	Issues []SlurmClusterIssue `json:"issues,omitempty"`
	// Login node Endpoint (IP).
	LoginNodeEndpoint string `json:"login_node_endpoint,omitempty"`
	// Nodeset IDs running the Slurm Workers.
	Nodesets []string `json:"nodesets,omitempty"`
	// State of the slurm cluster.
	State string `json:"state"`
}
