/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BulkCreateLocationInfo struct {
	// The ID of the Infiniband partition to create the VMs in, if an IB type was specified. Must be in the same location as the VMs.
	IbPartitionId string `json:"ib_partition_id,omitempty"`
	// The location to create the VMs in.
	Location string `json:"location"`
	// The ID of the subnet to create the VMs in. Must be in the same location as the VMs. If not provided, the default subnet for the location will be used, if there is one.
	SubnetId string `json:"subnet_id,omitempty"`
}
