/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExternalLoadBalancerPatchRequest struct {
	HealthCheckOptions *HealthCheckOptionsExternalLb `json:"health_check_options,omitempty"`
	// The ID of the External Load Balancer to update.
	Id string `json:"id"`
	// Listen ports and associated backends configuration.
	ListenPortsAndBackends []ListenPortAndBackend `json:"listen_ports_and_backends"`
}
