/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CcrTokenRequest struct {
	// Alias for the new token, used to identify it.
	Alias string `json:"alias,omitempty"`
	// Time at which the token expires.
	ExpiresAt string `json:"expires_at,omitempty"`
}
