/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SlurmClusterStatusPostRequest struct {
	// Issues describing why the cluster is not in STATE_RUNNING.
	Issues []SlurmClusterIssue `json:"issues,omitempty"`
	// Login node Endpoint (IP).
	LoginNodeEndpoint string `json:"login_node_endpoint,omitempty"`
	// Nodeset IDs running the Slurm Workers.
	Nodesets []string `json:"nodesets,omitempty"`
	// State of the slurm cluster.
	State string `json:"state"`
	// Size of the shared home volume as a Kubernetes quantity string.
	HomeVolumeSize string `json:"home_volume_size,omitempty"`
	// Number of replica pods to use for LoginSet.
	LoginReplicas int64                `json:"login_replicas,omitempty"`
	NodesetStatus []SlurmNodesetStatus `json:"nodeset_status,omitempty"`
	// Additional shared volumes attached to the cluster.
	Volumes []SlurmSharedVolume `json:"volumes,omitempty"`
}
