/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NotificationCategoryPreferences struct {
	// The category key.
	Category string `json:"category"`
	// Human-readable label for the category.
	CategoryDisplayName string `json:"category_display_name"`
	// Notification types within this category.
	Notifications []NotificationPreferenceItem `json:"notifications"`
}
