/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KubernetesClusterPatchRequest struct {
	// List of add-ons to be included to the cluster.
	AddOns []string `json:"add_ons,omitempty"`
	// Configuration setting of the Kubernetes cluster. Can only upgrade cluster to HA, but not downgrade from HA to normal
	Configuration string `json:"configuration"`
}
