/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VpcFirewallRule struct {
	Action           string               `json:"action"`
	DestinationPorts []string             `json:"destination_ports"`
	Destinations     []FirewallRuleObject `json:"destinations"`
	Direction        string               `json:"direction"`
	Id               string               `json:"id"`
	Name             string               `json:"name"`
	Protocols        []string             `json:"protocols"`
	SourcePorts      []string             `json:"source_ports"`
	Sources          []FirewallRuleObject `json:"sources"`
	State            string               `json:"state"`
	VpcNetworkId     string               `json:"vpc_network_id"`
}
