/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Entity struct {
	Billing          *Billing               `json:"billing"`
	BillingAddr      *BillingAddress        `json:"billing_addr,omitempty"`
	Features         map[string]interface{} `json:"features"`
	Id               string                 `json:"id"`
	MfaMethods       []string               `json:"mfa_methods,omitempty"`
	Name             string                 `json:"name"`
	OrganizationType string                 `json:"organization_type,omitempty"`
	RegistrationType string                 `json:"registration_type,omitempty"`
	Relation         string                 `json:"relation"`
	State            string                 `json:"state"`
	StateReason      string                 `json:"state_reason"`
}
