/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LatestDiagnosticResponse struct {
	CreatedAt     string `json:"created_at,omitempty"`
	HasDiagnostic bool   `json:"has_diagnostic"`
	Id            string `json:"id,omitempty"`
	UpdatedAt     string `json:"updated_at,omitempty"`
}
