/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SlurmSharedVolume struct {
	// Mount point for the volume (e.g. \"/data\").
	MountPoint string `json:"mount_point"`
	// Size of the volume in GiB.
	Size int64 `json:"size"`
}
