/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// It includes the one-time-only secret key.
type CreateS3KeyResponse struct {
	// The Access Key ID for S3 operations.
	AccessKeyId string `json:"access_key_id"`
	// Formatted timestamp for when the user access key expire.
	ExpireAt string `json:"expire_at,omitempty"`
	// The secret key. This is only shown once.
	SecretKey string `json:"secret_key"`
}
