/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExternalLoadBalancer struct {
	HealthCheckOptions *HealthCheckOptionsExternalLb `json:"health_check_options"`
	// ID of the External Load Balancer.
	Id string `json:"id"`
	// Listen ports and backends configuration.
	ListenPortsAndBackends []ListenPortAndBackend `json:"listen_ports_and_backends"`
	// Location of the External Load Balancer.
	Location string `json:"location"`
	// Name of the External Load Balancer.
	Name string `json:"name"`
	// The ID of the project this External Load Balancer belongs to.
	ProjectId string `json:"project_id"`
	// The protocol of the External Load Balancer.
	Protocol string `json:"protocol"`
	// Virtual IP (VIP) of the External Load Balancer.
	Vip string `json:"vip"`
	// The ID of the vpc network this External Load Balancer belongs to.
	VpcId string `json:"vpc_id"`
}
