/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CapacityV1Alpha5 struct {
	Location string `json:"location"`
	Quantity int32  `json:"quantity"`
	Type_    string `json:"type,omitempty"`
}
