/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NonHealthyVm struct {
	// Human-readable detail about the health status.
	Detail string `json:"detail"`
	// The reason code for the health status.
	Reason string `json:"reason"`
	// The health status (degraded, unhealthy, or not_evaluated).
	Status string `json:"status"`
	// The VM ID.
	VmId string `json:"vm_id"`
	// The VM name.
	VmName string `json:"vm_name"`
}
