/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateResponseEntry struct {
	// Name of the cluster the workflow runs on.
	ClusterName string `json:"cluster_name,omitempty"`
	// Error message, if the workflow could not be started.
	Error_ string `json:"error,omitempty"`
	// Region of the cluster.
	Region string `json:"region,omitempty"`
	// Temporal run ID.
	RunId string `json:"run_id,omitempty"`
	// Status of the triggered workflow.
	Status string `json:"status,omitempty"`
	// Temporal workflow ID.
	WorkflowId string `json:"workflow_id,omitempty"`
}
