/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VpcNetworkPostRequest struct {
	// Address range for the VPC network, in CIDR notation (for example, 172.27.0.0/16).
	Cidr string `json:"cidr"`
	// Name for the new VPC network.
	Name string `json:"name"`
}
