/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ListSSHKeysResponse is the response for listing the SSH keys registered to a user.
type CustomerListSshKeysResponse struct {
	Items []CustomerSshKey `json:"items,omitempty"`
}
