/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateDeploymentRequest struct {
	// Updated deployment name.
	DeploymentName string `json:"deployment_name,omitempty"`
	// Fine-tuned model (checkpoint) to switch the deployment to. Rolls the deployment onto the new checkpoint of the same base model.
	FineTunedModel string `json:"fine_tuned_model,omitempty"`
	// Updated replica count.
	Replicas int32 `json:"replicas,omitempty"`
	// Whether to roll out the change without downtime (rolling update) instead of recreating the deployment.
	RollingUpdate bool `json:"rolling_update,omitempty"`
}
