/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type KubernetesClusterPostRequest struct {
	// List of add-ons to be included to the cluster.
	AddOns []string `json:"add_ons,omitempty"`
	// defines: the range of IP Addresses allocated to pods scheduled on worker nodes
	ClusterCidr string `json:"cluster_cidr,omitempty"`
	// Configuration setting of the Kubernetes cluster. Leave the field empty for standard configuration.
	Configuration string `json:"configuration,omitempty"`
	// Location to create the Kubernetes cluster in.
	Location string `json:"location"`
	// Name of the Kubernetes cluster.
	Name string `json:"name"`
	// defines: the mask size for cluster cidr
	NodeCidrMaskSize int32 `json:"node_cidr_mask_size,omitempty"`
	// defines: the range of IP Addresses allocated to K8s services
	ServiceClusterIpRange string `json:"service_cluster_ip_range,omitempty"`
	// The ID of the subnet to create the cluster in. Must be in the location specified. If not provided, the default subnet for the location will be used, if there is one.
	SubnetId string `json:"subnet_id,omitempty"`
	// Version of the Crusoe Kubernetes image to create the cluster with.
	Version string `json:"version"`
}
