/*
 * Crusoe Cloud API Gateway
 *
 * The API Gateway exposes all publicly available API endpoints for Crusoe Cloud products.
 *
 * API version: v1alpha2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Entity struct {
	Billing  *Billing `json:"billing"`
	Features []string `json:"features"`
	Id       string   `json:"id"`
	Name     string   `json:"name"`
	Relation string   `json:"relation"`
}
