/*
 * rest-gateway
 *
 * Documentation of our REST API gateway that powers the user-facing website and CLI.
 *
 * API version: v1alpha1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Billing struct {
	Balance               string `json:"balance,omitempty"`
	Delinquent            bool   `json:"delinquent,omitempty"`
	HasValidPaymentMethod bool   `json:"has_valid_payment_method,omitempty"`
}
